main: com._14ercooper.worldeditor.main.Main
name: 14erEdit
version: 2.0.1
api-version: 1.14
description: A world editor created by 14er for use by the Minecraft mapmaking community, including the CTMC.
load: POSTWORLD
author: 14er
website: 14ercooper.com/edit

commands:
    fx:
        description: This is the root command for editing the world
        usage: "Usage: /fx <subcommands>"
    un:
        description: Undo edits to the world
        usage: "Usage: /un [number]"
    re:
        description: Redo edits to the world
        usage: "Usage: /re [number]"
    script:
        description: Handles the ability to use craftscripts
        usage: "Usage: /script <script> [args]"
        aliases: [cs]
    template:
        description: Load templates for faster brushes
        usage: "Usage: /template <file> [args...]"
        aliases: [tpl]
    run:
        description: Run an operation without a defined world position
        usage: "Usage: /run <operation>"
    funct:
        description: Run a 14erEdit function
        usage: "Usage: /funct <filename> [args...]"
    runat:
        description: Run a brush at a position
        usage: "Usage: /runat <x> <y> <z> <brush> <operation>"
    debug:
        description: Toggle debug messages globally
        usage: "Usage: /debug"
    error:
        description: Toggle verbose error messages globally
        usage: "Usage: /error"
    14erEdit:
        description: Display plugin information
        usage: "Usage: /14erEdit"
    async:
        description: Used to manage the async system
        usage: "Usage: /async <drop|status|dump>"
    make:
        description: Make different things using 14erEdit
        usage: "Usage: /make <type> [tags ...]"
    brmask:
        description: Change the brush mask
        usage: "Usage: /brmask [blocks ...]"
    limit:
        description: Change the XYZ limits on operations
        usage: "Usage: /limit <axis> <limit>"
    globalmask:
        description: Changes this player's global block mask
        usage: "Usage: /globalmask <block... | clear>"
