main: fourteener.worldeditor.main.Main
name: 14erEdit
version: 0.0.1-SNAPSHOT
api-version: 1.14
description: A world editor created by 14er for use by the Minecraft mapmaking community, including the CTMC.
load: POSTWORLD
author: 14er
website: 14ercooper.com/edit

commands: